# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "Tyler Rockwood's Site"
description: > # this means to ignore newlines until "baseurl:"
  Tyler Rockwood's website. Blog, projects + work.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.tylerrockwood.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed
permalink: pretty


